[colours]
bg_col = "#1b1b1b"
bg_sec = "#262626"
fg_col = "#9e9e9e"
fg_sec = "#616161"
hl_col = "#7cafc2"

[executables]
volume = "$HOME/Scripts/volume_slider"
workspace = "$HOME/Scripts/switch_focused_workspace"

[general]
height = 25
ws_icons = ""
power_icon = ""
font = "Fira Sans-12"
icon_font = "FontAwesome-12"
underline_height = 0
update_icon = ""

[placeholders]
general = "     "
power = "   "
workspace = "  "
clock = "          "
notification = "     "
volume = "     "
updates = "   "
music = "           "
